name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc dc coreutils build-essential
        sudo apt-get upgrade -y
        true  # Don't care.
    - name: make
      run: CC=gcc make clean all

